# Generated by Django 3.2.12 on 2024-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cheeses',
            field=models.CharField(choices=[('MZCH', 'Mozzarella'), ('VCH', 'Vegan cheese'), ('LFCH', 'low fat cheese')], default='MZCH', max_length=4),
        ),
        migrations.AddField(
            model_name='pizza',
            name='crusts',
            field=models.CharField(choices=[('NC', 'Normal Crust'), ('TNC', 'Thin crust'), ('TKC', 'Thick crust'), ('GFC', 'Gluten free crust')], default='NC', max_length=3),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'extra-large')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('P', 'Pepperoni'), ('C', 'Chicken'), ('H', 'Ham'), ('PL', 'Pineapple'), ('PE', 'Mushroomd'), ('O', 'Onions')], default='P', max_length=2),
        ),
    ]
