# Generated by Django 3.2.12 on 2024-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_cvv',
            field=models.IntegerField(default=0, verbose_name='security code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(default=0, verbose_name='card number'),
        ),
    ]
