# Generated by Django 3.2.12 on 2024-02-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_auto_20240214_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheeses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mozzarella', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sauces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mozzarella', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='medium', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='crusts',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='chicken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='ham',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='mushrooms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='onions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pepperoni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='peppers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pineapple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauces',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzaapp.sauces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheeses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaapp.cheeses'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaapp.sizes'),
        ),
    ]
