# Generated by Django 3.2.12 on 2024-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_auto_20240221_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_exp',
            field=models.IntegerField(default=0),
        ),
    ]
