# Generated by Django 3.2.12 on 2024-02-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_auto_20240216_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauces',
            name='name',
            field=models.CharField(default='tomato', max_length=20),
        ),
    ]
