# Generated by Django 3.2.12 on 2024-02-21 16:15

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_alter_order_card_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_exp',
            field=creditcards.models.CardExpiryField(verbose_name='card expiry'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(),
        ),
    ]
