# Generated by Django 3.2.12 on 2024-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_auto_20240221_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
