# Generated by Django 5.0.2 on 2024-02-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_auto_20240221_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_cvv',
            field=models.IntegerField(default=0, verbose_name='security code'),
        ),
    ]
